# Shallow Net in Keras

Buid a shallow neural network to classify MNIST digits

#### Set seed for reproducibily

In [1]:
import numpy as np
np.random.seed(42)

In [2]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [3]:
from keras.optimizers import SGD

#### Load Data

In [4]:
(X_train, y_train),(X_test, y_test) = mnist.load_data()

In [5]:
X_train.shape

(60000, 28, 28)

In [6]:
y_train.shape

(60000,)

In [7]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9,
       1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9,
       8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0,
       0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7,
       4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [8]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [9]:
y_test.shape

(10000,)

In [10]:
X_test.shape

(10000, 28, 28)

#### Preprocess data

In [11]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000,784).astype('float32')

In [12]:
X_train /= 255
X_test /= 255

In [13]:
X_train[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [14]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train,n_classes)
y_test = keras.utils.to_categorical(y_test,n_classes)

In [15]:
y_train[0]

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

#### Design neural network architecture

In [16]:
model = Sequential()
model.add(Dense((64), activation='sigmoid',input_shape=(784,)))
model.add(Dense((10), activation='softmax'))

In [17]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


#### Configure model

In [18]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [19]:
model.fit(X_train, y_train, batch_size=128,epochs=1,verbose=1,validation_data=(X_test,y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 3s - loss: 0.0915 - acc: 0.0895 - val_loss: 0.0911 - val_acc: 0.0955


In [20]:
model.fit(X_train, y_train, batch_size=128,epochs=200,verbose=1,validation_data=(X_test,y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 2s - loss: 0.0908 - acc: 0.1063 - val_loss: 0.0905 - val_acc: 0.1165
Epoch 2/200
60000/60000 [==============================] - 2s - loss: 0.0903 - acc: 0.1406 - val_loss: 0.0901 - val_acc: 0.1511
Epoch 3/200
60000/60000 [==============================] - 2s - loss: 0.0899 - acc: 0.1929 - val_loss: 0.0897 - val_acc: 0.2055
Epoch 4/200
60000/60000 [==============================] - 2s - loss: 0.0895 - acc: 0.2398 - val_loss: 0.0893 - val_acc: 0.2424
Epoch 5/200
60000/60000 [==============================] - 2s - loss: 0.0891 - acc: 0.2704 - val_loss: 0.0889 - val_acc: 0.2717
Epoch 6/200
60000/60000 [==============================] - 2s - loss: 0.0888 - acc: 0.2903 - val_loss: 0.0886 - val_acc: 0.2878
Epoch 7/200
60000/60000 [==============================] - 2s - loss: 0.0884 - acc: 0.3025 - val_loss: 0.0883 - val_acc: 0.3018
Epoch 8/200
60000/60000 [=============================

60000/60000 [==============================] - 2s - loss: 0.0638 - acc: 0.6151 - val_loss: 0.0632 - val_acc: 0.6189
Epoch 65/200
60000/60000 [==============================] - 3s - loss: 0.0633 - acc: 0.6190 - val_loss: 0.0627 - val_acc: 0.6223
Epoch 66/200
60000/60000 [==============================] - 2s - loss: 0.0629 - acc: 0.6218 - val_loss: 0.0623 - val_acc: 0.6254
Epoch 67/200
60000/60000 [==============================] - 2s - loss: 0.0624 - acc: 0.6252 - val_loss: 0.0618 - val_acc: 0.6277
Epoch 68/200
60000/60000 [==============================] - 2s - loss: 0.0620 - acc: 0.6284 - val_loss: 0.0613 - val_acc: 0.6309
Epoch 69/200
60000/60000 [==============================] - 2s - loss: 0.0615 - acc: 0.6320 - val_loss: 0.0609 - val_acc: 0.6338
Epoch 70/200
60000/60000 [==============================] - 3s - loss: 0.0611 - acc: 0.6348 - val_loss: 0.0604 - val_acc: 0.6364
Epoch 71/200
60000/60000 [==============================] - 2s - loss: 0.0606 - acc: 0.6371 - val_loss: 0.0600

60000/60000 [==============================] - 2s - loss: 0.0407 - acc: 0.7836 - val_loss: 0.0398 - val_acc: 0.7929
Epoch 128/200
60000/60000 [==============================] - 2s - loss: 0.0405 - acc: 0.7853 - val_loss: 0.0395 - val_acc: 0.7951
Epoch 129/200
60000/60000 [==============================] - 2s - loss: 0.0402 - acc: 0.7871 - val_loss: 0.0393 - val_acc: 0.7979
Epoch 130/200
60000/60000 [==============================] - 2s - loss: 0.0400 - acc: 0.7890 - val_loss: 0.0390 - val_acc: 0.7993
Epoch 131/200
60000/60000 [==============================] - 2s - loss: 0.0397 - acc: 0.7908 - val_loss: 0.0388 - val_acc: 0.8015
Epoch 132/200
60000/60000 [==============================] - 2s - loss: 0.0395 - acc: 0.7922 - val_loss: 0.0385 - val_acc: 0.8032
Epoch 133/200
60000/60000 [==============================] - 2s - loss: 0.0392 - acc: 0.7943 - val_loss: 0.0383 - val_acc: 0.8044
Epoch 134/200
60000/60000 [==============================] - 2s - loss: 0.0390 - acc: 0.7956 - val_loss:

60000/60000 [==============================] - 2s - loss: 0.0292 - acc: 0.8543 - val_loss: 0.0282 - val_acc: 0.8616
Epoch 191/200
60000/60000 [==============================] - 2s - loss: 0.0291 - acc: 0.8549 - val_loss: 0.0281 - val_acc: 0.8618
Epoch 192/200
60000/60000 [==============================] - 2s - loss: 0.0290 - acc: 0.8555 - val_loss: 0.0280 - val_acc: 0.8624
Epoch 193/200
60000/60000 [==============================] - 2s - loss: 0.0289 - acc: 0.8558 - val_loss: 0.0279 - val_acc: 0.8629
Epoch 194/200
60000/60000 [==============================] - 2s - loss: 0.0288 - acc: 0.8564 - val_loss: 0.0277 - val_acc: 0.8634
Epoch 195/200
60000/60000 [==============================] - 2s - loss: 0.0286 - acc: 0.8570 - val_loss: 0.0276 - val_acc: 0.8638
Epoch 196/200
60000/60000 [==============================] - 2s - loss: 0.0285 - acc: 0.8575 - val_loss: 0.0275 - val_acc: 0.8640
Epoch 197/200
60000/60000 [==============================] - 2s - loss: 0.0284 - acc: 0.8578 - val_loss: